name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/test.yaml
    with:
      run_tests: true
  publish:
    runs-on: ubuntu-latest
    needs: [tests]
    environment: release
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine build
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m build
        twine upload dist/*
